### ISSUE TITLE
ns.js throws strings instead of Errors

### ISSUE THREAD

**Issue by melvincarvalho** [linkeddata/solid-ui#3]
In attempting to clean up some of the files in solid.ui to conform with the [JS Standard](https://github.com/feross/standard) warnings of the kind are thrown: 

> _[solid-ui/lib/ns.js:14:26](https://github.com/linkeddata/solid-ui/blob/master/lib/ns.js#L14) : Expected an object to be thrown._

Code:

``` JavaScript
    throw 'Prefixed name has no colon: ' + prefixed
```

A possible solution may be to have code throw a **new Error()** instead.  As follows.

``` JavaScript
    throw new Error('Prefixed name has no colon: ' + prefixed)
```

There's also a note on [stackoverflow](http://stackoverflow.com/questions/11502052/throwing-strings-instead-of-errors) on this topic.

I've checked the [linkeddata](https://github.com/search?utf8=%E2%9C%93&q=org%3Alinkeddata+expand&type=Code&ref=searchresults) and [solid](https://github.com/search?utf8=%E2%9C%93&q=org%3Asolid+expand&type=Code&ref=searchresults) orgs for calls to the _expand_ function and didnt find anything.  Id be happy to make this change (add new Error) if it's unlikely to break anything.

**Comment by timbl** [comment]
Often the code catches an exception, and throws another adding an explanation string string like:
```
  catch(e) {
   throw "Error trying to update type index users profile file: " + e 
}
```
That would still work -- all that is needed is a string value .  In fact I recommend that as best practice. 

Unfortunately the Error object and the current best practices like http://www.javascriptkit.com/javatutors/trycatch2.shtml don't deal with a chain of errors,  but they should

Would be nice to have a standard property to pass back the causing error
```
  catch(e1) {
   throw { name: "Error", because: e1, message:  "Error trying to update type index users profile file: " + e }
}
```
But you have to get pass the history back in the string, as current systems don't know 'because' an you have to get the whole thing ideally back to the user so the user can ask someone what  it means or google it.

Conclusion: yes, we should switch to throwing errors, and accumulating message strings.

**Comment by melvincarvalho** [comment]
I noticed

> Promise rejection reasons should always be instances of the ECMAScript Error type, **just like synchronously-thrown exceptions should always be instances of Error as well**.

https://www.w3.org/2001/tag/doc/promises-guide

So great, I'll go ahead and put in a pull request to fix this file.
